### ISSUE TITLE
Disable auto commit for consumer groups

### ISSUE THREAD

**Issue by jamesharv** [heroku/heroku-kafka-jsplugin#192]
Is there a way to disable auto commit for a consumer group (as defined in the [Consumer Configs documentation](https://kafka.apache.org/documentation/#consumerconfigs) as `enable.auto.commit`)? I want to configure my consumer group so that each consumer can manually commit each offset after successfully processing a message.

If not, is it possible to add support for this? FYI this is for an application using a basic multi-tenanted Heroku Kafka plan. 

Thanks in advance

**Comment by uhoh-itsmaciek** [comment]
Hi James,

Can you please open a support ticket at https://help.heroku.com ? This repo is only for issues directly relating to the kafka CLI plugin functionality.
