### ISSUE TITLE
Drop confirmation prompt for creating replication factor 1 topics

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [heroku/heroku-kafka-jsplugin#73]
The lowest RF we allow now is 2 on `beta-dev`, so it doesn't make sense to have a confirmation for 1 when it's rejected server-side anyway.

**Comment by uhoh-itsmaciek** [comment]
Also the error messages from Shogun are strange, but that's a backend issue:

```
 ▸    replication_factor Replication Factor (4) is greater than the maximum allowed on this plan (3)
```

**Comment by tcrayford** [comment]
That's @hgmnz's fault
