### ISSUE TITLE
Rename topics:delete to topics:destroy?

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [heroku/heroku-kafka-jsplugin#74]
We have

 * `heroku create` and `heroku destroy`
 * `heroku addons:create` and `heroku addons:destroy`
 * `heroku orgs:create` and `heroku orgs:destroy`
 * `heroku pipelines:create` and `heroku pipelines:destroy`

and

 * `heroku kafka:topics:create` and `heroku kafka:topics:delete`

Thoughts on `delete` => `destroy`?

**Comment by justindowning** [comment]
+1 ...imo `delete` could lead to the assumption of an `undelete` feature, whereas `destroy` is 💥

**Comment by rand** [comment]
👍

**Comment by idan** [comment]
👍

**Comment by uhoh-itsmaciek** [comment]
Fixed by #78
