### ISSUE TITLE
Remove "Connections" from "kafka:info"

### ISSUE THREAD

**Issue by thody** [heroku/heroku-kafka-jsplugin#94]
The connections detail in `kafka:info` is confusing/inaccurate. Let's remove it for now, and considering fixing it and adding it back in the future.

Further context: https://heroku.slack.com/archives/dod-kcz/p1473811559000986

**Comment by uhoh-itsmaciek** [comment]
This output comes directly from Shogun. I can still patch it there since it's a UX issue, but the CLI is basically a dumb pipe for a series of `info` items from Shogun (we can rethink that, but let's not tackle that now). I'll close this and open a Shogun issue.
